# This is a basic workflow to help you get started with Actionsghghj

name: test Action Secrets

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      shell: bash
      env:
        jiraToken: ${{ secrets.JIRA_TOKEN }}
        envVariable: yes it is
      run: |
        pwd
        echo $envVariable
        echo $jiraToken
        curl https://loose.atlassian.net/rest/api/2/application-properties -u "mario.rivis@gmail.com:$jiraToken"
  
  docker-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: Mario Rivis
    steps:
      - name: Create Results folder
        run: mkdir output
      - name: Run Docker image
        run: docker run -v `pwd`/output:/root/test/output --env GITHUB_USER=mario mario94/actions-test:latest
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: result-file
          path: output
    
    
